# Generated by Django 3.0.4 on 2020-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('totalConfirmed', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('totalRecovered', models.IntegerField()),
                ('dailyConfirmed', models.IntegerField()),
                ('dailyDeaths', models.IntegerField()),
                ('activeCases', models.IntegerField()),
                ('totalCritical', models.IntegerField()),
                ('totalConfirmedPerMillionPopulation', models.IntegerField()),
                ('totalDeathsPerMillionPopulation', models.IntegerField()),
                ('FR', models.FloatField()),
                ('PR', models.FloatField()),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCtracker_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalConfirmed', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('totalRecovered', models.IntegerField()),
                ('totalNewCases', models.IntegerField()),
                ('totalNewDeaths', models.IntegerField()),
                ('totalActiveCases', models.IntegerField()),
                ('totalCasesPerMillionPop', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otpgenrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
