# Generated by Django 3.0.4 on 2020-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajranapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCoronatracker_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalConfirmed', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('totalRecovered', models.IntegerField()),
                ('totalNewCases', models.IntegerField()),
                ('totalNewDeaths', models.IntegerField()),
                ('totalActiveCases', models.IntegerField()),
                ('totalCasesPerMillionPop', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
